//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NetModel.proto
namespace NetModel
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"model")]
  public partial class model : global::ProtoBuf.IExtensible
  {
    public model() {}
    
    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Commit = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Commit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Commit
    {
      get { return _Commit; }
      set { _Commit = value; }
    }
    private string _Message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}