//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: W_NoticeInfoRes.proto
namespace W_NoticeInfoRes
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"W_NoticeInfoRes")]
  public partial class W_NoticeInfoRes : global::ProtoBuf.IExtensible
  {
    public W_NoticeInfoRes() {}
    
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _errorCode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private string _errorString = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorString
    {
      get { return _errorString; }
      set { _errorString = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _remainSec = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"remainSec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainSec
    {
      get { return _remainSec; }
      set { _remainSec = value; }
    }
    private long _nowTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nowTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long nowTime
    {
      get { return _nowTime; }
      set { _nowTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}