//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: W_NoticeInfoReq.proto
namespace W_NoticeInfoReq
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"W_NoticeInfoReq")]
  public partial class W_NoticeInfoReq : global::ProtoBuf.IExtensible
  {
    public W_NoticeInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}